# Generated by Django 3.2.9 on 2021-12-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='posts.post'),
            preserve_default=False,
        ),
    ]
